// Fill out your copyright notice in the Description page of Project Settings.


#include "Build/AC_BuildComponent.h"
#include "BuildInterface.h"
#include "Character/EmberCharacter.h"
#include "ALSCamera/Public/AlsCameraComponent.h"
#include "Blueprint/UserWidget.h"
#include "Components/BoxComponent.h"
#include "Components/Image.h"
#include "Components/TextBlock.h"
#include "Components/ProgressBar.h"
#include "EmberLog/EmberLog.h"

// Sets default values for this component's properties
UAC_BuildComponent::UAC_BuildComponent()
{
	// Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
	// off to improve performance if you don't need them.
	PrimaryComponentTick.bCanEverTick = false;
	static ConstructorHelpers::FObjectFinder<UDataTable> DataTableRef(TEXT("/Script/Engine.DataTable'/Game/_Data/BuildingSystem/DT_Buildable.DT_Buildable'"));
	if (DataTableRef.Succeeded())
	{
		BuildData = DataTableRef.Object;

	}
	static ConstructorHelpers::FClassFinder<UUserWidget> WidgetClassFinder(TEXT("/Game/_Data/BuildingSystem/BuildUI/UI_BuildPreview.UI_BuildPreview_C")); // í™•ì¥ì _C ë¶™ì´ê¸° í•„ìˆ˜
	if (WidgetClassFinder.Succeeded())
	{
		BuildPreviewWidgetClass = WidgetClassFinder.Class;
	}
	else {
		UE_LOG(LogTemp, Warning, TEXT("BuildPreviewWidgetClass not found!"));
	}
	static ConstructorHelpers::FClassFinder<UUserWidget> WidgetClassFinder1(TEXT("/Game/_Data/BuildingSystem/BuildUI/UI_BuildHealth.UI_BuildHealth_C"));
	if (WidgetClassFinder1.Succeeded())
	{
		BuildHealthWidgetClass = WidgetClassFinder1.Class;
	}
	else {
		UE_LOG(LogTemp, Warning, TEXT("BuildHealthWidgetClass not found!"));
	}
}


// Called when the game starts
void UAC_BuildComponent::BeginPlay()
{
	Super::BeginPlay();

	AActor* Owner = GetOwner();
	if (Owner)
	{
		PlayerReference = Cast<AEmberCharacter>(Owner);
	}

	if (!BuildData)
	{
		return;
	}
	TArray<FName> RowNames = BuildData->GetRowNames();
	for (const FName& RowName : RowNames)
	{
		static const FString ContextString(TEXT("BuildDataContext")); //È¤ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
		FBuildableData* Row = BuildData->FindRow<FBuildableData>(RowName, ContextString);

		if (Row)
		{
			Buildables.Add(*Row);
		}
	}

	if (BuildPreviewWidgetClass)
	{
		BuildPreviewWidget = CreateWidget<UUserWidget>(GetWorld(), BuildPreviewWidgetClass);
		if (BuildPreviewWidget)
		{
			BuildPreviewWidget->AddToViewport();
			BuildPreviewWidget->SetVisibility(ESlateVisibility::Hidden); // ê¸°ë³¸ì€ ìˆ¨ê¹€
		}
	}
	if (BuildHealthWidgetClass)
	{
		BuildHealthWidget = CreateWidget<UUserWidget>(GetWorld(), BuildHealthWidgetClass);
		if (BuildHealthWidget)
		{
			BuildHealthWidget->AddToViewport();
			BuildHealthWidget->SetVisibility(ESlateVisibility::Hidden); // ê¸°ë³¸ì€ ìˆ¨ê¹€
		}
	}
}


// Called every frame
void UAC_BuildComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// ...
}

void UAC_BuildComponent::SpawnBuildGoust()
{
	if (!PlayerReference || !Buildables.IsValidIndex(BuildID))
	{
		UE_LOG(LogTemp, Warning, TEXT("Invalid PlayerReference or BuildID"));
		return;
	}

	// BuildGhost ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® ï¿½ï¿½ï¿½ï¿½
	BuildGhost = NewObject<UStaticMeshComponent>(PlayerReference);
	if (!BuildGhost)
	{
		UE_LOG(LogTemp, Warning, TEXT("Failed to create BuildGhost component"));
		return;
	}

	BuildGhost->RegisterComponent(); // ï¿½ï¿½ï¿½å¿¡ ï¿½ï¿½ï¿½
	BuildGhost->AttachToComponent(PlayerReference->GetRootComponent(), FAttachmentTransformRules::KeepRelativeTransform);
	BuildGhost->SetRelativeTransform(BuildTransform);

	// Static Mesh ï¿½ï¿½ï¿½ï¿½
	const FBuildableData& Data = Buildables[BuildID];
	BuildGhost->SetStaticMesh(Data.Mesh);

	// ï¿½æµ¹ ï¿½ï¿½È°ï¿½ï¿½È­
	BuildGhost->SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

void UAC_BuildComponent::LaunchBuildMode()
{
	if (bIsBuildModeOn)
	{
		StopBuildMode();
		bIsBuildModeOn = false;
		return;
	}

	bIsBuildModeOn = true;

	BuildCycle();
}

void UAC_BuildComponent::BuildDelay()
{
	if (!bIsBuildModeOn)
	{
		StopBuildMode();
		bIsBuildModeOn = false;
		return;
	}

	// 0.01ï¿½ï¿½ ï¿½ï¿½ BuildCycle È£ï¿½ï¿½
	GetWorld()->GetTimerManager().SetTimer(BuildDelayHandle, this, &UAC_BuildComponent::BuildCycle, 0.01f, false);
}

void UAC_BuildComponent::BuildCycle()
{
	if (!Camera || Buildables.Num() <= BuildID) return;
	
	FVector WorldLocation;
	FVector WorldDirection;
	if (APlayerController* PC = GetWorld()->GetFirstPlayerController())
	{
		int32 ViewportSizeX, ViewportSizeY;
		PC->GetViewportSize(ViewportSizeX, ViewportSizeY);
		
		FVector2D ScreenCenter(ViewportSizeX * 0.5f, ViewportSizeY * 0.5f);
		
		PC->DeprojectScreenPositionToWorld(
			ScreenCenter.X,
			ScreenCenter.Y,
			WorldLocation,
			WorldDirection
		);
	}
	
	// 2. ï¿½ï¿½ï¿½ï¿½Æ®ï¿½ï¿½ï¿½Ì½ï¿½ ï¿½ï¿½ï¿½ï¿½/ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	FVector Start = WorldLocation + WorldDirection * 350.f;
	FVector End   = WorldLocation + WorldDirection * 1000.f;

	// 3. ï¿½ï¿½ï¿½ï¿½Æ®ï¿½ï¿½ï¿½Ì½ï¿½
	FHitResult HitResult;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(GetOwner()); // ï¿½Ú½ï¿½ ï¿½ï¿½ï¿½ï¿½
	Params.bTraceComplex = false;

	// Buildablesï¿½ï¿½ï¿½ï¿½ TraceChannel ï¿½ï¿½ï¿½ï¿½
	ECollisionChannel TraceChannel = ECC_Visibility; // ï¿½âº» Ã¤ï¿½ï¿½
	if (Buildables.IsValidIndex(BuildID))
	{

		TraceChannel = UEngineTypes::ConvertToCollisionChannel(Buildables[BuildID].TraceChannel);
	}

	bool bHit = GetWorld()->LineTraceSingleByChannel(
		HitResult,
		Start,
		End,
		TraceChannel,
		Params
	);
	if (bHit)
	{
		BuildTransform.SetLocation(HitResult.ImpactPoint);
		// âœ… ìˆ˜ì •ëœ íšŒì „ ì²˜ë¦¬ (ì¹´ë©”ë¼ê°€ ë°”ë¼ë³´ëŠ” ë°©í–¥ì˜ Yawë§Œ ìœ ì§€)
		FRotator LookRotation = WorldDirection.Rotation();
		LookRotation.Pitch = 0.f;
		LookRotation.Roll = 0.f;
		BuildTransform.SetRotation(FQuat(LookRotation));

		HitActor = HitResult.GetActor();
		HitComponent = HitResult.GetComponent();
		if (IsValid(BuildGhost))
		{
			FTransform TempTransform;
			Found = DetectBuildBoxes(TempTransform);
			if (Found)
			{
				BuildTransform = TempTransform;
			}
			GiveBuildColor(true);
		}
		else
		{
			SpawnBuildGoust();
		}
	}
	else
	{
		BuildTransform.SetLocation(End);
		BuildTransform.SetRotation(WorldDirection.ToOrientationQuat());
		HitActor = nullptr;
		HitComponent = nullptr;
		if (IsValid(BuildGhost))
		{
			GiveBuildColor(false);
		}
		else
		{
			SpawnBuildGoust();
		}
	}

	UpdateBuildPreviewUI();

	BuildDelay();
}

void UAC_BuildComponent::StopBuildMode()
{
	bIsBuildModeOn = false;
	bCanBuild = false;

	if (IsValid(BuildGhost) && PlayerReference)
	{
		BuildGhost->DestroyComponent();
		BuildGhost = nullptr;
	}

	if (BuildPreviewWidget)
	{
		BuildPreviewWidget->SetVisibility(ESlateVisibility::Hidden);
	}

}

void UAC_BuildComponent::GiveBuildColor(bool bIsGreen)
{
	bCanBuild = bIsGreen;

	if (!BuildGhost) return;

	// 2. BuildGhostï¿½ï¿½ ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ È®ï¿½ï¿½
	int32 MaterialCount = BuildGhost->GetNumMaterials();
	
	/*
	static ConstructorHelpers::FObjectFinder<UMaterialInstance> GreenMatObj(TEXT("/Script/Engine.MaterialInstanceConstant'/Game/_Art/_EasyBuilding/Materials/Instances/Dummy/MI_Can_Build.MI_Can_Build'"));
	static ConstructorHelpers::FObjectFinder<UMaterialInstance> RedMatObj(TEXT("/Script/Engine.MaterialInstanceConstant'/Game/_Art/_EasyBuilding/Materials/Instances/Dummy/MI_CanNot_Build.MI_CanNot_Build'"));
	if (GreenMatObj.Succeeded())
	{
		GreenMaterial = GreenMatObj.Object;
	}
	if (RedMatObj.Succeeded())
	{
		RedMaterial = RedMatObj.Object;
	}*/
	
	// 3. ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ ï¿½Îµï¿½ï¿½ï¿½ ï¿½ï¿½È¸ï¿½Ï¸ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
	for (int32 i = 0; i < MaterialCount; ++i)
	{
		if (bIsGreen)
		{
			BuildGhost->SetMaterial(i, GreenMaterial); // GreenMaterialï¿½ï¿½ UMaterialInterface*
		}
		else
		{
			BuildGhost->SetMaterial(i, RedMaterial);   // RedMaterialï¿½ï¿½ UMaterialInterface*
		}
	}

	// 4. ï¿½ï¿½Ä¡ ï¿½ï¿½ï¿½ï¿½
	BuildGhost->SetWorldTransform(BuildTransform, false, nullptr, ETeleportType::None);
}
void UAC_BuildComponent::SpwanBuild()
{
	if (!bCanBuild)
	{
		return;
	}
	
	// ï¿½ï¿½È¿ï¿½ï¿½ ï¿½Ë»ï¿½
	if (!Buildables.IsValidIndex(BuildID))
	{
		UE_LOG(LogTemp, Warning, TEXT("Invalid BuildID: %d"), BuildID);
		return;
	}

	// ï¿½Ø´ï¿½ ï¿½Îµï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	const FBuildableData& Data = Buildables[BuildID];

	if (!Data.Actor)
	{
		UE_LOG(LogTemp, Warning, TEXT("Buildables[%d] has no Actor class"), BuildID);
		return;
	}

	// Actor ï¿½ï¿½ï¿½ï¿½
	FActorSpawnParameters SpawnParams;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;

	AActor* SpawnedActor = GetWorld()->SpawnActor<AActor>(
		Data.Actor,
		BuildTransform,
		SpawnParams
	);

	if (!SpawnedActor)
	{
		UE_LOG(LogTemp, Warning, TEXT("Failed to spawn actor from Buildables[%d]"), BuildID);
		return;
	}

	// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì½ï¿½ï¿½ï¿½ Ä³ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ SetMesh È£ï¿½ï¿½
	if (SpawnedActor->GetClass()->ImplementsInterface(UBuildInterface::StaticClass()))
	{
		IBuildInterface::Execute_SetMesh(SpawnedActor, Data.Mesh);
		IBuildInterface::Execute_SetHealth(SpawnedActor, Data.Health);
		
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("Spawned actor does not implement BuildInterface"));
	}
	if (SpawnedActor)
	{

		// ì €ì¥ìš© êµ¬ì¡°ì²´ êµ¬ì„±
		FBuildSaveData SaveData;
		SaveData.ActorClassPath = Data.Actor->GetClass()->GetPathName();  // ê²½ë¡œ ì €ì¥
		SaveData.Location = SpawnedActor->GetActorLocation();
		SaveData.Rotation = SpawnedActor->GetActorRotation();
		SaveData.Scale = SpawnedActor->GetActorScale3D();

		SavedBuildDataArray.Add(SaveData);
	}
}
void UAC_BuildComponent::ChangeMesh()
{
	if (!BuildGhost || !Buildables.IsValidIndex(BuildID))
	{
		UE_LOG(LogTemp, Warning, TEXT("Invalid BuildGhost or PlayerReference or BuildID"));
		return;
	}
	const FBuildableData& Data = Buildables[BuildID];
	if (Data.Mesh)
	{
		BuildGhost->SetStaticMesh(Data.Mesh);
		UpdateBuildPreviewUI();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("No mesh found for BuildID: %d"), BuildID);
	}
}

bool UAC_BuildComponent::DetectBuildBoxes(FTransform& OutTransform)
{
	// 1. ï¿½ï¿½È¿ï¿½ï¿½ ï¿½Ë»ï¿½
	if (!HitActor || !HitComponent)
	{
		return false;
	}

	// 2. ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ È®ï¿½ï¿½
	if (!HitActor->GetClass()->ImplementsInterface(UBuildInterface::StaticClass()))
	{
		return false;
	}

	// 3. BuildInterfaceï¿½ï¿½ ReturnBoxes È£ï¿½ï¿½
	TArray<UBoxComponent*> BuildBoxes = IBuildInterface::Execute_ReturnBoxes(HitActor);

	// 4. ï¿½İºï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ HitComponentï¿½ï¿½ ï¿½ï¿½ï¿½ÔµÇ¾ï¿½ ï¿½Ö´ï¿½ï¿½ï¿½ È®ï¿½ï¿½
	for (UBoxComponent* Box : BuildBoxes)
	{
		if (Box == Cast<UBoxComponent>(HitComponent))
		{
			OutTransform = HitComponent->GetComponentTransform();
			return true; // LocalFound = true
		}
	}

	// 5. ï¿½ï¿½ Ã£ï¿½ï¿½ ï¿½ï¿½ï¿½
	return false; // LocalFound = false
}

void UAC_BuildComponent::SaveBuilds()
{
	FString SaveSlot = TEXT("BuildSlot");

	// SaveGame ì˜¤ë¸Œì íŠ¸ ìƒì„±
	UBuildSaveGame* SaveObject = Cast<UBuildSaveGame>(
		UEMSFunctionLibrary::GetCustomSave(this, UBuildSaveGame::StaticClass(), SaveSlot, TEXT("BuildData"))
	);

	if (SaveObject)
	{
		SaveObject->SavedBuilds = SavedBuildDataArray; // í˜„ì¬ ì €ì¥ëœ ê±´ë¬¼ ë°°ì—´ ë³µì‚¬
		UEMSFunctionLibrary::SaveCustom(this, SaveObject); // ì‹¤ì œ ì €ì¥ ìˆ˜í–‰
	}
}

void UAC_BuildComponent::LoadBuilds()
{
	FString SaveSlot = TEXT("BuildSlot");

	UBuildSaveGame* SaveObject = Cast<UBuildSaveGame>(
		UEMSFunctionLibrary::GetCustomSave(this, UBuildSaveGame::StaticClass(), SaveSlot, TEXT("BuildData"))
	);

	if (SaveObject)
	{
		SavedBuildDataArray = SaveObject->SavedBuilds;

		// ë°°ì—´ì„ ë°”íƒ•ìœ¼ë¡œ ì•¡í„° ì¬ë°°ì¹˜
		for (const FBuildSaveData& Data : SavedBuildDataArray)
		{
			FActorSpawnParameters Params;
			UClass* BuildClass = LoadClass<AActor>(nullptr, *Data.ActorClassPath);
			if (BuildClass)
			{
				AActor* SpawnedActor = GetWorld()->SpawnActor<AActor>(
					BuildClass,
					Data.Location,
					Data.Rotation,
					Params
				);

				if (SpawnedActor)
				{
					SpawnedActor->SetActorScale3D(Data.Scale);
				}
			}
		}
	}
}

void UAC_BuildComponent::RepairBuilding()
{
	FoundBuild();
	if (!bIsBuildModeOn || !HitActor)
	{
		UE_LOG(LogTemp, Warning, TEXT("Build Mode OFF or No HitActor"));
		return;
	}

	// BuildInterface í™•ì¸
	if (!HitActor->GetClass()->ImplementsInterface(UBuildInterface::StaticClass()))
	{
		UE_LOG(LogTemp, Warning, TEXT("HitActor does not implement BuildInterface"));
		return;
	}
	// í˜„ì¬ Actorì˜ Class Pathë¡œ DataTableì—ì„œ BuildData ì°¾ê¸°
	FString ClassPath = HitActor->GetClass()->GetPathName();
	FBuildableData* FoundData = nullptr;

	for (FBuildableData& Data : Buildables)
	{
		if (Data.Actor && Data.Actor->GetPathName() == ClassPath)
		{
			FoundData = &Data;
			break;
		}
	}

	if (!FoundData)
	{
		UE_LOG(LogTemp, Warning, TEXT("Matching BuildableData not found"));
		return;
	}

	// í˜„ì¬ ì²´ë ¥ ê°€ì ¸ì˜¤ê¸° (ì¸í„°í˜ì´ìŠ¤ë¡œ ì²´ë ¥ ê°€ì ¸ì˜¤ê¸° í•„ìš”)
	float CurrentHealth = IBuildInterface::Execute_GetHealth(HitActor);
	float MaxHealth = FoundData->Health;

	if (CurrentHealth >= MaxHealth)
	{
		UE_LOG(LogTemp, Log, TEXT("Already at full health"));
		UpdateHealth(CurrentHealth, MaxHealth);
		return;
	}

	// ìì› í™•ì¸ (í”Œë ˆì´ì–´ ì¸ë²¤í† ë¦¬ ì‹œìŠ¤í…œì´ í•„ìš”. ì„ì‹œë¡œ boolë¡œ ê°€ì •)
	bool bHasResources = true; // ì—¬ê¸°ì— ì¸ë²¤í† ë¦¬ ì²´í¬ ë¡œì§ ì‚½ì…
	if (!bHasResources)
	{
		UE_LOG(LogTemp, Warning, TEXT("Not enough resources to repair"));
		return;
	}

	// ìì› ì†Œë¹„ (ë¦¬ì†ŒìŠ¤ ì‹œìŠ¤í…œê³¼ ì—°ë™ í•„ìš”)
	// ì˜ˆ: ConsumeResource(FoundData->RequiredResources, FoundData->RequiredResourceAmounts);

	// ìˆ˜ë¦¬ëŸ‰ ê²°ì • (ê°„ë‹¨íˆ ê³ ì •ê°’ì´ë‚˜ %ë¡œ ê°€ëŠ¥)
	float RepairAmount = 20.0f; // ì˜ˆ: ê³ ì • ìˆ˜ë¦¬ëŸ‰

	float NewHealth = FMath::Clamp(CurrentHealth + RepairAmount, 0.0f, MaxHealth);
	IBuildInterface::Execute_SetHealth(HitActor, NewHealth);

	UE_LOG(LogTemp, Log, TEXT("Repaired %s to %.1f / %.1f"), *HitActor->GetName(), NewHealth, MaxHealth);

	UpdateHealth(NewHealth, MaxHealth);
}

void UAC_BuildComponent::UpdateBuildPreviewUI()
{
	if (!BuildPreviewWidget || !Buildables.IsValidIndex(BuildID))
	{
		return;
	}

	BuildPreviewWidget->SetVisibility(ESlateVisibility::Visible);

	const FBuildableData& Data = Buildables[BuildID];

	UImage* ThumbnailImage = Cast<UImage>(BuildPreviewWidget->GetWidgetFromName(TEXT("BuildThumbnail")));
	UTextBlock* DescText = Cast<UTextBlock>(BuildPreviewWidget->GetWidgetFromName(TEXT("BuildDescriptionText")));

	if (ThumbnailImage && Data.Thumbnail)
	{
		ThumbnailImage->SetBrushFromTexture(Data.Thumbnail);
	}
	if (DescText)
	{
		DescText->SetText(Data.BuildableDescription);
	}
}

void UAC_BuildComponent::UpdateHealth(float CurrentHealth, float MaxHealth)
{
	if (!BuildHealthWidget)
	{
		return;
	}

	BuildHealthWidget->SetVisibility(ESlateVisibility::Visible);

	const FBuildableData& Data = Buildables[BuildID];

	UProgressBar* HealthBar = Cast<UProgressBar>(BuildHealthWidget->GetWidgetFromName(TEXT("HealthBar")));
	UTextBlock* HealthText = Cast<UTextBlock>(BuildHealthWidget->GetWidgetFromName(TEXT("HealthText")));

	if (HealthBar)
	{
		HealthBar->SetPercent(CurrentHealth / MaxHealth);
	}

	if (HealthText)
	{
		FString Text = FString::Printf(TEXT("%.0f / %.0f"), CurrentHealth, MaxHealth);
		HealthText->SetText(FText::FromString(Text));
	}
	// ğŸ”½ 2ì´ˆ í›„ ìˆ¨ê¸°ê¸°
	if (BuildHealthWidget)
	{
		GetWorld()->GetTimerManager().ClearTimer(HealthWidgetHideTimerHandle); // ì´ì „ íƒ€ì´ë¨¸ ì œê±°
		GetWorld()->GetTimerManager().SetTimer(HealthWidgetHideTimerHandle, [this]()
			{
				if (BuildHealthWidget)
				{
					BuildHealthWidget->SetVisibility(ESlateVisibility::Hidden);
				}
			}, 1.0f, false);
	}
	UE_LOG(LogTemp, Warning, TEXT("Complete UI"));
}

void UAC_BuildComponent::FoundBuild()
{

	FVector WorldLocation;
	FVector WorldDirection;
	if (APlayerController* PC = GetWorld()->GetFirstPlayerController())
	{
		int32 ViewportSizeX, ViewportSizeY;
		PC->GetViewportSize(ViewportSizeX, ViewportSizeY);

		FVector2D ScreenCenter(ViewportSizeX * 0.5f, ViewportSizeY * 0.5f);

		PC->DeprojectScreenPositionToWorld(
			ScreenCenter.X,
			ScreenCenter.Y,
			WorldLocation,
			WorldDirection
		);
	}
	FVector Start = WorldLocation + WorldDirection * 350.f;
	FVector End = WorldLocation + WorldDirection * 1000.f;

	FHitResult HitResult;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(PlayerReference);

	bool bHit = GetWorld()->LineTraceSingleByChannel(
		HitResult,
		Start,
		End,
		ECollisionChannel::ECC_Visibility, // ê±´ë¬¼ ì „ìš© íŠ¸ë ˆì´ìŠ¤ ì±„ë„ ì‚¬ìš© ì¶”ì²œ
		Params
	);

	if (bHit)
	{
		UE_LOG(LogTemp, Warning, TEXT("Hit: %s"), *HitResult.GetActor()->GetName());
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("LineTrace failed"));
	}

	if (bHit && HitResult.GetActor())
	{
		AActor* HitTarget = HitResult.GetActor();
		if (HitTarget->GetClass()->ImplementsInterface(UBuildInterface::StaticClass()))
		{
			HitActor = HitTarget; // âœ… ìˆ˜ë¦¬ ëŒ€ìƒ ì„¤ì •
		}
	}
	else
	{
		HitActor = nullptr;
	}
}
